// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxviXFKul4kwrtn-pizIHp7DSFZ6L96QM',
    appId: '1:725009112175:web:43edee9265ef2ccb29c19a',
    messagingSenderId: '725009112175',
    projectId: 'bdesmovil',
    authDomain: 'bdesmovil.firebaseapp.com',
    storageBucket: 'bdesmovil.firebasestorage.app',
    measurementId: 'G-N6RJ7VT5C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQrxvwrpxIwYX8SfKuu02CJIl07P9Oj4',
    appId: '1:725009112175:android:22d772ee610b707229c19a',
    messagingSenderId: '725009112175',
    projectId: 'bdesmovil',
    storageBucket: 'bdesmovil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCh3CA_eH29wSQjgeiRFreSOhAaCzDgA4',
    appId: '1:725009112175:ios:d432e647693f48b929c19a',
    messagingSenderId: '725009112175',
    projectId: 'bdesmovil',
    storageBucket: 'bdesmovil.firebasestorage.app',
    iosBundleId: 'com.example.copylogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCh3CA_eH29wSQjgeiRFreSOhAaCzDgA4',
    appId: '1:725009112175:ios:d432e647693f48b929c19a',
    messagingSenderId: '725009112175',
    projectId: 'bdesmovil',
    storageBucket: 'bdesmovil.firebasestorage.app',
    iosBundleId: 'com.example.copylogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxviXFKul4kwrtn-pizIHp7DSFZ6L96QM',
    appId: '1:725009112175:web:5e29a8ff94d2141229c19a',
    messagingSenderId: '725009112175',
    projectId: 'bdesmovil',
    authDomain: 'bdesmovil.firebaseapp.com',
    storageBucket: 'bdesmovil.firebasestorage.app',
    measurementId: 'G-JR8WWV4KBK',
  );
}
